name: CI
on:
  pull_request:
  push:

jobs:
  build-wayland:
    name: Build Wayland libraries
    runs-on: ubuntu-latest
    env:
      seatd-version: "0.5.0"
    strategy:
      matrix:
        wayland-version: ["1.19.0"]
        wayland-protocols-version: ["1.21"]
        wlroots-version: ["8ca2b4cf49055eabcd2499bf3811d356d769bded", master]
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y --no-install-recommends \
            libdrm-dev \
            libegl1-mesa-dev \
            libgbm-dev \
            libgles2-mesa-dev \
            libinput-dev \
            libxcb-composite0-dev \
            libxcb-dri3-dev \
            libxcb-icccm4-dev \
            libxcb-image0-dev \
            libxcb-render0-dev \
            libxcb-xfixes0-dev \
            libxcb-xinput-dev \
            libxcb1-dev \
            libxkbcommon-dev \
            ninja-build
          sudo pip install meson
      - name: Set environment variables
        run: |
          echo "CPATH=${HOME}/wayland/usr/include" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=${HOME}/wayland/usr/lib" >> $GITHUB_ENV
          echo "LIBRARY_PATH=${HOME}/wayland/usr/lib" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=${HOME}/wayland/usr/share/pkgconfig:${HOME}/wayland/usr/lib/pkgconfig" >> $GITHUB_ENV
      - name: Download and unpack Wayland source
        run: |
          wget $WAYLAND_URL
          wget $WAYLAND_PROTOCOLS_URL
          wget -O seatd.tar.gz $SEATD_URL
          wget -O wlroots.tar.gz $WLROOTS_URL
          tar -xJf wayland-${{ matrix.wayland-version }}.tar.xz
          tar -xJf wayland-protocols-${{ matrix.wayland-protocols-version }}.tar.xz
          tar -xzf seatd.tar.gz
          tar -xzf wlroots.tar.gz
        env:
          WAYLAND_URL: https://wayland.freedesktop.org/releases/wayland-${{ matrix.wayland-version }}.tar.xz
          WAYLAND_PROTOCOLS_URL: https://wayland.freedesktop.org/releases/wayland-protocols-${{ matrix.wayland-protocols-version }}.tar.xz
          SEATD_URL: https://git.sr.ht/~kennylevinsen/seatd/archive/${{ env.seatd-version }}.tar.gz
          WLROOTS_URL: https://github.com/swaywm/wlroots/archive/${{ matrix.wlroots-version }}.tar.gz
      - name: Build wayland
        working-directory: wayland-${{ matrix.wayland-version }}
        run: |
          ./configure --disable-documentation --prefix=/usr
          make
          DESTDIR=~/wayland make install
          sudo make install
      - name: Build wayland-protocols
        working-directory: wayland-protocols-${{ matrix.wayland-protocols-version }}
        run: |
          ./configure --prefix=/usr
          make
          DESTDIR=~/wayland make install
          sudo make install
      - name: Build seatd
        working-directory: seatd-${{ env.seatd-version }}
        if: ${{ matrix.wlroots-version == 'master' }}
        run: |
          meson build --prefix=/usr
          ninja -C build
          DESTDIR=~/wayland ninja -C build install
          sudo ninja -C build install
      - name: Build wlroots
        working-directory: wlroots-${{ matrix.wlroots-version }}
        run: |
          meson build --prefix=/usr
          ninja -C build
          DESTDIR=~/wayland ninja -C build install
      - name: Create artifact
        run: tar czf ~/wayland.tar.gz -C ${HOME}/wayland/ .
      - name: Upload built libraries
        uses: actions/upload-artifact@v2
        with:
          name: wayland-${{ matrix.wayland-version }}_${{ matrix.wayland-protocols-version }}_${{ matrix.wlroots-version }}
          path: ~/wayland.tar.gz
          if-no-files-found: error
  unit-test:
    name: Python ${{ matrix.python-version}} unit tests
    runs-on: ubuntu-latest
    needs: build-wayland
    strategy:
      matrix:
        python-version: [pypy3, "3.6", "3.7", "3.8", "3.9"]
        wayland-version: ["1.19.0"]
        wayland-protocols-version: ["1.21"]
        wlroots-version: ["0.13.0"]
        include:
          - python-version: "3.9"
            wayland-version: "1.19.0"
            wayland-protocols-version: "1.21"
            wlroots-version: master
    steps:
      - name: Download wayland libraries
        uses: actions/download-artifact@v2
        with:
          name: wayland-${{ matrix.wayland-version }}_${{ matrix.wayland-protocols-version }}_${{ matrix.wlroots-version }}
      - name: Unpack wayland artifact
        run: sudo tar xf wayland.tar.gz -C /
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y --no-install-recommends \
            libdrm-dev \
            libegl1-mesa-dev \
            libgbm-dev \
            libgles2-mesa-dev \
            libinput-dev \
            libxcb-composite0-dev \
            libxcb-dri3-dev \
            libxcb-icccm4-dev \
            libxcb-image0-dev \
            libxcb-render0-dev \
            libxcb-xfixes0-dev \
            libxcb-xinput-dev \
            libxcb1-dev \
            libxkbcommon-dev
      - name: Set environment variables
        run: |
          echo "XDG_RUNTIME_DIR=/tmp" >> $GITHUB_ENV
      - name: Install Python dependencies
        continue-on-error: ${{ matrix.wlroots-version == 'master' }}
        run: |
          pip install -r requirements.txt
          pip install pytest
          python wlroots/ffi_build.py
      - name: Run unit tests
        continue-on-error: ${{ matrix.wlroots-version == 'master' }}
        run: pytest -Wall
        env:
          WLR_BACKENDS: "headless"
          WLR_HEADLESS_OUTPUTS: "2"
          WLR_LIBINPUT_NO_DEVICES: "1"
          WLR_RENDERER_ALLOW_SOFTWARE: "1"
          WLR_RENDERER: "pixman"
  flake8-test:
    name: Python ${{ matrix.python-version}} flake8 tests
    runs-on: ubuntu-latest
    needs: build-wayland
    strategy:
      matrix:
        python-version: ["3.9"]
        wayland-version: ["1.19.0"]
        wayland-protocols-version: ["1.21"]
        wlroots-version: ["0.13.0"]
    steps:
      - name: Download wayland libraries
        uses: actions/download-artifact@v2
        with:
          name: wayland-${{ matrix.wayland-version }}_${{ matrix.wayland-protocols-version }}_${{ matrix.wlroots-version }}
      - name: Unpack wayland artifact
        run: sudo tar xf wayland.tar.gz -C /
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y --no-install-recommends \
            libdrm-dev \
            libegl1-mesa-dev \
            libgbm-dev \
            libgles2-mesa-dev \
            libinput-dev \
            libxcb-composite0-dev \
            libxcb-dri3-dev \
            libxcb-icccm4-dev \
            libxcb-image0-dev \
            libxcb-render0-dev \
            libxcb-xfixes0-dev \
            libxcb-xinput-dev \
            libxcb1-dev \
            libxkbcommon-dev
      - name: Set environment variables
        run: |
          echo "XDG_RUNTIME_DIR=/tmp" >> $GITHUB_ENV
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8
          python wlroots/ffi_build.py
      - name: Run flake8 test
        run: flake8 wlroots tiny
  mypy-test:
    name: Python ${{ matrix.python-version}} mypy tests
    runs-on: ubuntu-latest
    needs: build-wayland
    strategy:
      matrix:
        python-version: ["3.9"]
        wayland-version: ["1.19.0"]
        wayland-protocols-version: ["1.21"]
        wlroots-version: ["0.13.0"]
    steps:
      - name: Download wayland libraries
        uses: actions/download-artifact@v2
        with:
          name: wayland-${{ matrix.wayland-version }}_${{ matrix.wayland-protocols-version }}_${{ matrix.wlroots-version }}
      - name: Unpack wayland artifact
        run: sudo tar xf wayland.tar.gz -C /
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y --no-install-recommends \
            libdrm-dev \
            libegl1-mesa-dev \
            libgbm-dev \
            libgles2-mesa-dev \
            libinput-dev \
            libxcb-composite0-dev \
            libxcb-dri3-dev \
            libxcb-icccm4-dev \
            libxcb-image0-dev \
            libxcb-render0-dev \
            libxcb-xfixes0-dev \
            libxcb-xinput-dev \
            libxcb1-dev \
            libxkbcommon-dev
      - name: Set environment variables
        run: |
          echo "XDG_RUNTIME_DIR=/tmp" >> $GITHUB_ENV
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install mypy
          python wlroots/ffi_build.py
      - name: Run mypy test
        run: |
          mypy -p wlroots
          mypy -p tiny --python-version 3.7
